apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: block-pvc
  namespace: ivolve
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: ""