apiVersion: v1
kind: Service
metadata:
  name: nodejs-service-init
  namespace: ivolve
spec:
  type: ClusterIP
  selector:
    app: nodejs-app-init
  ports:
  - port: 80
    targetPort: 3000
    protocol: TCP
    name: http
